use std::collections::BTreeMap;

use soma_zero::{
    ChairCalibrationRecommendation, ChairCalibrationReport, ChairDiagnosticsSummary,
    CommitteeDecisionQualityReport, CommitteeDecisionQualityStatus, CommitteeEvidenceQualityReport,
    CommitteeEvidenceQualityStatus, CommitteeReplayReport, CommitteeScenarioSet,
    CommitteeV1FinalStatus, CommitteeV1NextRecommendation, CommitteeV1ReadinessReport,
    CommitteeV1ReadinessStatus, CommitteeV1ReportBundle, PersonaConflictMatrix,
    PersonaConflictStatus, ReasonCode, RiskCalibrationRecommendation, RiskCalibrationReport,
    RiskDiagnosticsSummary,
};

#[test]
fn committee_v1_bundle_contains_core_reports_and_is_deterministic() {
    let bundle = CommitteeV1ReportBundle {
        run_id: "bundle".to_string(),
        scenario_set: Some(CommitteeScenarioSet {
            scenario_id: "bundle".to_string(),
            rows: Vec::new(),
            source_summary: "Fixture".to_string(),
            row_count: 0,
            official_row_count: 0,
            research_only_row_count: 0,
            fixture_row_count: 0,
            skipped_row_count: 0,
            reason_codes: vec![ReasonCode::CommitteeScenarioLoaderBuilt],
        }),
        replay_report: CommitteeReplayReport {
            replay_id: "bundle".to_string(),
            records: Vec::new(),
            record_count: 0,
            source_summary: "Fixture".to_string(),
            final_action_counts: BTreeMap::new(),
            risk_denial_counts: BTreeMap::new(),
            chair_decision_counts: BTreeMap::new(),
            deterministic_fingerprint: "fp".to_string(),
            reason_codes: vec![ReasonCode::CommitteeReplayBuilt],
        },
        chair_diagnostics_summary: ChairDiagnosticsSummary {
            report_count: 0,
            status_counts: BTreeMap::new(),
            warnings: Vec::new(),
            reports: Vec::new(),
            reason_codes: vec![ReasonCode::CommitteeV1BundleBuilt],
        },
        risk_diagnostics_summary: RiskDiagnosticsSummary {
            report_count: 0,
            status_counts: BTreeMap::new(),
            veto_count: 0,
            warnings: Vec::new(),
            reports: Vec::new(),
            reason_codes: vec![ReasonCode::CommitteeV1BundleBuilt],
        },
        conflict_matrix: PersonaConflictMatrix {
            pairs: Vec::new(),
            most_aligned_pairs: Vec::new(),
            most_conflicted_pairs: Vec::new(),
            average_disagreement: 0.0,
            groupthink_frequency: 0.0,
            conflict_status: PersonaConflictStatus::InsufficientSamples,
            reason_codes: vec![ReasonCode::PersonaConflictMatrixBuilt],
        },
        evidence_quality_report: CommitteeEvidenceQualityReport {
            source_summary: "Fixture".to_string(),
            official_count: 0,
            crypto_only_count: 0,
            yfinance_research_count: 0,
            fixture_count: 0,
            synthetic_test_count: 0,
            missing_provenance_count: 0,
            low_quality_count: 0,
            scenario_count: 0,
            enough_for_design_review: false,
            quality_status: CommitteeEvidenceQualityStatus::FixtureOnlyEvidence,
            warnings: Vec::new(),
            reason_codes: vec![ReasonCode::CommitteeEvidenceQualityBuilt],
        },
        decision_quality_report: CommitteeDecisionQualityReport {
            decision_count: 0,
            source_summary: "Fixture".to_string(),
            final_action_counts: BTreeMap::new(),
            chair_decision_counts: BTreeMap::new(),
            persona_stance_counts: BTreeMap::new(),
            no_trade_ratio: 1.0,
            approve_candidate_ratio: 0.0,
            reduce_size_ratio: 0.0,
            require_confirm_ratio: 0.0,
            risk_denial_ratio: 0.0,
            hard_veto_ratio: 0.0,
            emergency_stop_ratio: 0.0,
            cooldown_ratio: 0.0,
            groupthink_warning_ratio: 0.0,
            high_disagreement_ratio: 0.0,
            average_disagreement: 0.0,
            average_uncertainty: 0.0,
            average_weighted_score: 0.0,
            average_expected_edge_after_cost: 0.0,
            average_expected_drawdown: 0.0,
            data_quality_distribution: BTreeMap::new(),
            evidence_quality_status: CommitteeEvidenceQualityStatus::FixtureOnlyEvidence,
            quality_status: CommitteeDecisionQualityStatus::InsufficientSamples,
            reason_codes: vec![ReasonCode::CommitteeDecisionQualityBuilt],
        },
        chair_calibration_report: ChairCalibrationReport {
            suggestions: Vec::new(),
            groupthink_suggestions: Vec::new(),
            disagreement_suggestions: Vec::new(),
            speaker_filter_suggestions: Vec::new(),
            cluster_penalty_suggestions: Vec::new(),
            contrarian_inclusion_suggestions: Vec::new(),
            final_recommendation: ChairCalibrationRecommendation::NeedMoreEvidence,
            reason_codes: vec![ReasonCode::ChairCalibrationBuilt],
        },
        risk_calibration_report: RiskCalibrationReport {
            suggestions: Vec::new(),
            overblocking_suspected: false,
            underblocking_suspected: false,
            final_recommendation: RiskCalibrationRecommendation::NeedMoreEvidence,
            reason_codes: vec![ReasonCode::RiskCalibrationBuilt],
        },
        v1_readiness_report: CommitteeV1ReadinessReport {
            status: CommitteeV1ReadinessStatus::NotReadyTooFewSamples,
            evidence_quality_status: CommitteeEvidenceQualityStatus::FixtureOnlyEvidence,
            decision_quality_status: CommitteeDecisionQualityStatus::InsufficientSamples,
            chair_status: "NeedMoreEvidence".to_string(),
            risk_status: "NeedMoreEvidence".to_string(),
            conflict_status: PersonaConflictStatus::InsufficientSamples,
            sample_count: 0,
            official_sample_count: 0,
            research_only_ratio: 0.0,
            fixture_ratio: 1.0,
            groupthink_ratio: 0.0,
            risk_denial_ratio: 0.0,
            enough_samples: false,
            blockers: vec!["not enough committee samples".to_string()],
            warnings: Vec::new(),
            next_recommendation: CommitteeV1NextRecommendation::NeedMoreEvidence,
            reason_codes: vec![ReasonCode::CommitteeV1ReadinessBuilt],
        },
        audit_summary: "audit".to_string(),
        storage_summary: None,
        final_status: CommitteeV1FinalStatus::CommitteeV1NeedsEvidence,
        final_recommendation: CommitteeV1NextRecommendation::NeedMoreEvidence,
        warnings: Vec::new(),
        reason_codes: vec![ReasonCode::CommitteeV1BundleBuilt],
    };
    let text = bundle.to_text();
    assert!(text.contains("final_status=CommitteeV1NeedsEvidence"));
    assert_eq!(text, bundle.to_text());
}
